# The command that is going to be executed when player is detected with flood
# By default is set to do nothing, use %name% to specify exploiters nickname (for example, 'ban %name%')
dispatchCommand: 'ban %name%'

# The reason why player was kicked
kickMessage: 'You tried to exploit CustomPayload packet'

# Enable or disabling additional detail log to plugin data folder
EnableCustomLog: true

# The format of custom log message. See https://docs.oracle.com/javase/8/docs/api/java/util/logging/SimpleFormatter.html#format-java.util.logging.LogRecord-
CustomLogFormat: "[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS %4$s]: %5$s%6$s%n"